---
title: "Lokaverkefni-Gervigreind"
author: "Ævar Ingi Jóhannesson"
date: "4/6/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```

```{r, warning = F, message = F}
library(plyr); library(dplyr); library(lubridate)
library(ggplot2)
library(grid)
library(gridExtra)
library(glmnet)
library(e1071)
library(randomForest)
library(knitr)
library(gbm)
library(corrplot)
library(caret)
library(mlbench)
library(tictoc)
library(gdata)
```

## Load data:

```{r}
data = read.csv("train.csv")
data$id = NULL
data.submit = read.csv("test.csv")
id = data.submit$id
```

```{r}
#Check for NA values
dim(na.omit(data)) == dim(data)
```

```{r}
#Check distribution of response
density1 <- ggplot(data,aes(loss))+
  geom_density(fill = "palegreen2", alpha = 0.4) 

density2 <- ggplot(data,aes(log(loss)))+
  geom_density(fill = "skyblue", alpha = 0.4)

grid.arrange(density1,density2,nrow=2)
```

```{r}
skewness(data$loss)
skewness(log(data$loss))
data$loss = log(data$loss)
```

## Descriptive plots

```{r}
#Continuous variables
p1 = ggplot(data=data, aes(x=cont2,y=loss))+
      geom_point(size=0.4)+ylab("log(loss)")

p2 = ggplot(data=data, aes(x=cont3,y=loss))+
      geom_point(size=0.4)+ylab("log(loss)")

p3 = ggplot(data=data, aes(x=cont13,y=loss))+
      geom_point(size=0.4)+ylab("log(loss)")

p4 = ggplot(data=data, aes(x=cont14,y=loss))+
      geom_point(size=0.4)+ylab("log(loss)")

grid.arrange(p1,p2,p3,p4,nrow = 2)
```

```{r}
#Boxplots of categorical variables
b1 = ggplot(data=data, aes(x=cat7,y=loss))+
  geom_boxplot(outlier.size = 0.5)+ylab("log(loss)")

b2 = ggplot(data=data, aes(x=cat87,y=loss))+
  geom_boxplot(outlier.size = 0.5)+ylab("log(loss)")

b3 = ggplot(data=data, aes(x=cat89,y=loss))+
  geom_boxplot(outlier.size = 0.5)+ylab("log(loss)")

b4 = ggplot(data=data, aes(x=cat100,y=loss))+
  geom_boxplot(outlier.size = 0.5)+ylab("log(loss)")

b5 = ggplot(data=data, aes(x=cat101,y=loss))+
  geom_boxplot(outlier.size = 0.5)+ylab("log(loss)")

b6 = ggplot(data=data, aes(x=cat103,y=loss))+
  geom_boxplot(outlier.size = 0.5)+ylab("log(loss)")

b7 = ggplot(data=data, aes(x=cat104,y=loss))+
  geom_boxplot(outlier.size = 0.5)+ylab("log(loss)")

b8 = ggplot(data=data, aes(x=cat113,y=loss))+
  geom_boxplot(outlier.size = 0.5)+ylab("log(loss)")

grid.arrange(b1,b2,b3,b4,nrow = 2)
grid.arrange(b5,b6,b7,b8,nrow = 2)
```

## Correlation

```{r}
data.cont = data[,117:131]
cormat = cor(data.cont[,-15])
corrplot(cormat, method = "circle")

#drop highly correlated variables
data$cont9 = NULL
data$cont12 = NULL
```

```{r}
data.try = data

#Remove those categories with observations under 10
#fer bara í gegnum alla, gerist ekkert ef > 10 mælingar
for(i in 1:116){
  var = eval(parse(text = paste("data.try$cat",as.character(i),sep="")))
  data.try = data.try[var %in% names(which(table(var) > 10)), ]
}

data.try = droplevels(data.try)
```

```{r}
#gamall kóði - ekki keyra
data.try = data.try[data.try$cat75 %in% names(which(table(data.try$cat75) > 10)), ]
data.try = data.try[data.try$cat88 %in% names(which(table(data.try$cat88) > 10)), ]
data.try = data.try[data.try$cat89 %in% names(which(table(data.try$cat89) > 10)), ]
data.try = data.try[data.try$cat90 %in% names(which(table(data.try$cat90) > 10)), ]
data.try = data.try[data.try$cat92 %in% names(which(table(data.try$cat92) > 10)), ]
data.try = data.try[data.try$cat99 %in% names(which(table(data.try$cat99) > 10)), ]
data.try = data.try[data.try$cat101 %in% names(which(table(data.try$cat101) > 10)), ]
data.try = data.try[data.try$cat102 %in% names(which(table(data.try$cat102) > 10)), ]
data.try = data.try[data.try$cat103 %in% names(which(table(data.try$cat103) > 10)), ]
data.try = data.try[data.try$cat104 %in% names(which(table(data.try$cat104) > 10)), ]
data.try = data.try[data.try$cat105 %in% names(which(table(data.try$cat105) > 10)), ]
data.try = data.try[data.try$cat106 %in% names(which(table(data.try$cat106) > 10)), ]
data.try = data.try[data.try$cat107 %in% names(which(table(data.try$cat107) > 10)), ]
data.try = data.try[data.try$cat109 %in% names(which(table(data.try$cat109) > 10)), ]
data.try = data.try[data.try$cat110 %in% names(which(table(data.try$cat110) > 10)), ]
data.try = data.try[data.try$cat111 %in% names(which(table(data.try$cat111) > 10)), ]
data.try = data.try[data.try$cat113 %in% names(which(table(data.try$cat113) > 10)), ]
data.try = data.try[data.try$cat114 %in% names(which(table(data.try$cat114) > 10)), ]
data.try = data.try[data.try$cat115 %in% names(which(table(data.try$cat115) > 10)), ]
data.try = data.try[data.try$cat116 %in% names(which(table(data.try$cat116) > 10)), ]

data.try$cat75  = droplevels(data.try$cat75) ; data.try$cat88  = droplevels(data.try$cat88)
data.try$cat89  = droplevels(data.try$cat89) ; data.try$cat90  = droplevels(data.try$cat90)
data.try$cat92  = droplevels(data.try$cat92) ; data.try$cat99  = droplevels(data.try$cat99)
data.try$cat101 = droplevels(data.try$cat101); data.try$cat102 = droplevels(data.try$cat102)
data.try$cat103 = droplevels(data.try$cat103); data.try$cat104 = droplevels(data.try$cat104)
data.try$cat105 = droplevels(data.try$cat105); data.try$cat106 = droplevels(data.try$cat106)
data.try$cat107 = droplevels(data.try$cat107); data.try$cat109 = droplevels(data.try$cat109)
data.try$cat110 = droplevels(data.try$cat110); data.try$cat111 = droplevels(data.try$cat111)
data.try$cat113 = droplevels(data.try$cat113); data.try$cat114 = droplevels(data.try$cat114)
data.try$cat115 = droplevels(data.try$cat115); data.try$cat116 = droplevels(data.try$cat116)

#Take variables with NA.
cat74 = data.try$cat74; data.try$cat74 = NULL
cat81 = data.try$cat81; data.try$cat81 = NULL
cat85 = data.try$cat85; data.try$cat85 = NULL
cat87 = data.try$cat87; data.try$cat87 = NULL
cat89 = data.try$cat89; data.try$cat89 = NULL
cat90 = data.try$cat90; data.try$cat90 = NULL
cat91 = data.try$cat91; data.try$cat91 = NULL
cat92 = data.try$cat92; data.try$cat92 = NULL
cat98 = data.try$cat98; data.try$cat98 = NULL
cat99 = data.try$cat99; data.try$cat99 = NULL
cat100 = data.try$cat100; data.try$cat100 = NULL 
cat101 = data.try$cat101; data.try$cat101 = NULL 
cat102 = data.try$cat102; data.try$cat102 = NULL
cat103 = data.try$cat103; data.try$cat103 = NULL 
cat104 = data.try$cat104; data.try$cat104 = NULL 
cat106 = data.try$cat106; data.try$cat106 = NULL
cat107 = data.try$cat107; data.try$cat107 = NULL
cat108 = data.try$cat108; data.try$cat108 = NULL
cat111 = data.try$cat111; data.try$cat111 = NULL
cat113 = data.try$cat113; data.try$cat113 = NULL
cat114 = data.try$cat114; data.try$cat114 = NULL
cat116 = data.try$cat116; data.try$cat116 = NULL
```
``

## Linear regression

```{r}
#Split to train and test.
set.seed(5)
n = dim(data.try)[1]
train = sample(n,floor(n*0.7))
data.train = data.try[train,]
data.test = data.try[-train,]

lm.try = lm(loss~.,data.train)
pred.try = predict(lm.try,data.test)
MAE.try = mean(abs(exp(data.test$loss) - exp(pred.try)))
MAE.try 

pred.sub = predict(lm.try,data.submit) 

fix = c(75,88,89,90,92,96,99,101,103,104,105,106,107,109,110,111,113,114,115,116)
for(i in 1:length(fix)){
  string = paste("cat",as.character(fix[i]),sep = "")
  var = eval(parse(text = paste("data.submit$cat",as.character(fix[i]),sep="")))
  lm.try$xlevels[[string]] <- union(lm.try$xlevels[[string]], levels(var))
}
```

```{r}
#gamall kóði - ekki keyra
lm.try$xlevels[["cat75"]] <- union(lm.try$xlevels[["cat75"]], levels(data.submit$cat75))
lm.try$xlevels[["cat88"]] <- union(lm.try$xlevels[["cat88"]], levels(data.submit$cat88))
lm.try$xlevels[["cat89"]] <- union(lm.try$xlevels[["cat89"]], levels(data.submit$cat89))
lm.try$xlevels[["cat90"]] <- union(lm.try$xlevels[["cat90"]], levels(data.submit$cat90))
lm.try$xlevels[["cat92"]] <- union(lm.try$xlevels[["cat92"]], levels(data.submit$cat92))
lm.try$xlevels[["cat96"]] <- union(lm.try$xlevels[["cat96"]], levels(data.submit$cat96))
lm.try$xlevels[["cat99"]] <- union(lm.try$xlevels[["cat99"]], levels(data.submit$cat99))
lm.try$xlevels[["cat101"]] <- union(lm.try$xlevels[["cat101"]], levels(data.submit$cat101))
lm.try$xlevels[["cat103"]] <- union(lm.try$xlevels[["cat103"]], levels(data.submit$cat103))
lm.try$xlevels[["cat104"]] <- union(lm.try$xlevels[["cat104"]], levels(data.submit$cat104))
lm.try$xlevels[["cat105"]] <- union(lm.try$xlevels[["cat105"]], levels(data.submit$cat105))
lm.try$xlevels[["cat106"]] <- union(lm.try$xlevels[["cat106"]], levels(data.submit$cat106))
lm.try$xlevels[["cat107"]] <- union(lm.try$xlevels[["cat107"]], levels(data.submit$cat107))
lm.try$xlevels[["cat109"]] <- union(lm.try$xlevels[["cat109"]], levels(data.submit$cat109))
lm.try$xlevels[["cat110"]] <- union(lm.try$xlevels[["cat110"]], levels(data.submit$cat110))
lm.try$xlevels[["cat111"]] <- union(lm.try$xlevels[["cat111"]], levels(data.submit$cat111))
lm.try$xlevels[["cat113"]] <- union(lm.try$xlevels[["cat113"]], levels(data.submit$cat113))
lm.try$xlevels[["cat114"]] <- union(lm.try$xlevels[["cat114"]], levels(data.submit$cat114))
lm.try$xlevels[["cat115"]] <- union(lm.try$xlevels[["cat115"]], levels(data.submit$cat115))
lm.try$xlevels[["cat116"]] <- union(lm.try$xlevels[["cat116"]], levels(data.submit$cat116))
```



##Lasso

```{r}
set.seed(1000)
ydata.train = data.matrix(data.train[,"loss"])
Xdata.train = data.matrix(data.train[,!(colnames(data.train) %in% c("loss"))])
Xdata.test = data.matrix(data.test[,!(colnames(data.train) %in% c("loss"))])
grid = 10^seq(4, -20, length=1000)
fit.lasso = cv.glmnet(Xdata.train,
                      ydata.train,
                      alpha=1,
                      lambda=grid,
                      thresh=1e-12)
plot(fit.lasso)

best.lambda=fit.lasso$lambda.min
pred.lasso = predict(fit.lasso,Xdata.test,s=best.lambda)
MAELasso = mean(abs(exp(data.test$loss) - exp(pred.lasso)))
MAELasso

#Create a data set from non-zero coefs from Lasso
coefs_temp <- predict(fit.lasso, s = fit.lasso$lambda.1se, type = "coefficients")
coefs_temp2 <- data.frame(name = coefs_temp@Dimnames[[1]][coefs_temp@i + 1], coefficient = coefs_temp@x)
names <- levels(coefs_temp2[,1])
names <- names[2:length(names)]
names <- c(names,"loss")
names
data.lasso = data.try[,names]
data.lasso.train = data.lasso[train,]
data.lasso.test = data.lasso[-train,]
```

##Boosting.

```{r}
#Create a validation set for grid search
n3 = dim(data.train)[1]
val = sample(n3,floor(0.2*n3)) 
data.val = data.train[val,]
data.train = data.train[-val,]
```

```{r}
#Grid Search.
set.seed(1000)
lambd <-  seq(0.001, 0.01, by=0.003)
lambd <- c(lambd,seq(0.04,0.2,by=0.08))
ntree <- seq(200,800,by=200)
ntree <- c(ntree,seq(1000,3000,by=250))
depth <- c(1,2,4,6,8)
m <- length(lambd)
l <- length(ntree)
t <- length(depth)
testErr <- array(dim=c(m,l,t))
for (i in 1:m){
  for(d in 1:t){
      boostCol = gbm(loss ~., data = data.train,
                      distribution = "gaussian",
                      n.trees = 3000,
                      shrinkage = lambd[i],
                      interaction.depth = depth[d])
      for(k in 1:l){
      testPred = predict(boostCol,
                         data.val,
                         n.trees = ntree[k])
      testErr[i,k,d] = mean(abs(exp(data.val$loss) - exp(testPred)))
      }
  print(i)
  }
}

which(testErr == min(testErr),arr.ind = T)
### lam = 0.1,d=8,ntree=3000
bestlam = lambd[4]
bestntree = ntree[13]
bestdepth = depth[5]
testErr
lambd
ntree
bestLam = lambd[which.min(testErr)]

MAEplotNtree = testErr[4,,5]
MAEplotInt = testErr[4,13,]

boostPlot =ggplot(data.frame(x=ntree,y=MAEplotNtree), aes(x=x, y=y)) +
            xlab("number of trees") + 
            ylab("Validation MAE") + 
            geom_point()+
            geom_line()
boostPlot

boostPlot2 =ggplot(data.frame(x=depth,y=MAEplotInt), aes(x=x, y=y)) +
            xlab("Interaction Depth") + 
            ylab("Validation MAE") + 
            geom_point()+
            geom_line()
boostPlot2

grid.arrange(boostPlot,
             boostPlot2,ncol=2)
```

```{r,eval = T}
set.seed(1000)
boost.fit <- gbm(loss ~ ., data = data.train,
                 distribution = "gaussian",
                 n.trees = bestntree,
                 shrinkage =bestlam,
                 interaction.depth = bestdepth)
boost.pred <- predict(boost.fit,
                      data.test,
                      n.trees = bestntree)
boost.pred2 <- predict(boost.fit,
                      data.submit,
                      n.trees = bestntree)
MAEBoost = mean(abs(exp(data.test$loss) - exp(boost.pred)))
MAEBoost 

#1154.547
#Kaggle: 1156.38
```


##Linear a Lasso modelið

```{r}
lm.try.lasso = lm(loss~.,data.lasso.train)
pred.try.lasso = predict(lm.try.lasso,data.lasso.test)
MAE.try = mean(abs(exp(data.lasso.test$loss) - exp(pred.try.lasso)))
MAE.try 
#1236.39 .

pred.sub = predict(lm.try.lasso,data.submit) #virkar ekki
lm.try.lasso$xlevels[["cat101"]] <- union(lm.try.lasso$xlevels[["cat101"]], levels(data.submit$cat101))
lm.try.lasso$xlevels[["cat103"]] <- union(lm.try.lasso$xlevels[["cat103"]], levels(data.submit$cat103))
lm.try.lasso$xlevels[["cat105"]] <- union(lm.try.lasso$xlevels[["cat105"]], levels(data.submit$cat105))
lm.try.lasso$xlevels[["cat111"]] <- union(lm.try.lasso$xlevels[["cat111"]], levels(data.submit$cat111))
lm.try.lasso$xlevels[["cat114"]] <- union(lm.try.lasso$xlevels[["cat114"]], levels(data.submit$cat114))
lm.try.lasso$xlevels[["cat75"]] <- union(lm.try.lasso$xlevels[["cat75"]], levels(data.submit$cat75))
lm.try.lasso$xlevels[["cat88"]] <- union(lm.try.lasso$xlevels[["cat88"]], levels(data.submit$cat88))
lm.try.lasso$xlevels[["cat92"]] <- union(lm.try.lasso$xlevels[["cat92"]], levels(data.submit$cat92))
lm.try.lasso$xlevels[["cat99"]] <- union(lm.try.lasso$xlevels[["cat99"]], levels(data.submit$cat99))

#Kaggle gefur: 1932.29996
```



## Boosting a Lasso modelið.
1225.86
með lambda 0.45 og n.trees 600

með lamda 0.05 og ntree 2500
1224.54568


```{r}
n3 = dim(data.lasso.train)[1]
val = sample(n3,floor(0.2*n3)) 
data.lasso.val = data.lasso.train[val,]
data.lasso.train = data.lasso.train[-val,]
```

```{r}
set.seed(1000)
lambd <-  seq(0.001, 0.01, by=0.002)
lambd <- c(lambd,seq(0.01,0.13,by=0.04))
ntree <- seq(200,800,by=200)
ntree <- c(ntree,seq(1000,2000,by=250))
depth <- c(1,2,4,6,8)
m <- length(lambd)
l <- length(ntree)
t <- length(depth)
testErr2 <- array(dim=c(m,l,t))
for (i in 1:m){
  for(d in 1:t){
      boostCol = gbm(loss ~., data = data.lasso.train,
                      distribution = "gaussian",
                      n.trees = 2000,
                      shrinkage = lambd[i],
                      interaction.depth = depth[d])
      for(k in 1:l){
      testPred = predict(boostCol,
                         data.lasso.val,
                         n.trees = ntree[k])
      testErr2[i,k,d] = mean(abs(exp(data.lasso.val$loss) - exp(testPred)))
      print(i)
      }
  }
}
testErr2
#Lambda = 0.05 og ntree = 2500
best.lambd = lambd[7]
best.ntree = ntree[9]

#teikna upp besta lambda með MAE sem fall af ntrees.
plot.lambd = testErr2[7,]
plot.lambd.data = data.frame(plot.lambd,ntree)
ggplot(data=plot.lambd.data,aes(x=ntree,y=plot.lambd))+
  geom_point()+
  geom_line()+
  xlab("Number of trees")+
  ylab("MAE")
```

```{r}
set.seed(1000)
boost.fit.small <- gbm(loss ~ ., data = data.lasso,
                 distribution = "gaussian",
                 n.trees = best.ntree, shrinkage =best.lambd)
boost.pred.small <- predict(boost.fit.small,
                      data.submit,
                      n.trees = best.ntree)
MAEBoost.small = mean(abs(exp(data.lasso.test$loss) - exp(boost.pred.small)))
MAEBoost.small 
```





##SUBMIT

```{r}
pred.submit = predict(fit.lm,data.submit.cat)
Submit= data.frame(id,loss=exp(boost.pred2))
names(Submit)[2] <- "loss"
write.csv(Submit,file="Submit.csv",row.names=FALSE)
```

